### ISSUE TITLE
starting bluetooth.service causes a permission error after applying the postinst

### ISSUE THREAD

**Issue by marcb1309** [EdNekebno/DGTCentaur#98]
Not sure in detail what changed between Buster and Bullseye but 

sudo systemctl bluetooth status shows:

pi@dgtcentaur:~/backup $ sudo systemctl restart bluetooth.service && sudo systemctl status bluetooth.service
● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; disabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-01-01 13:32:35 CET; 445ms ago
       Docs: man:bluetoothd(8)
   Main PID: 22096 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 415)
        CPU: 258ms
     CGroup: /system.slice/bluetooth.service
             └─22096 /usr/libexec/bluetooth/bluetoothd

Jan 01 13:32:35 raspberrypi systemd[1]: Starting Bluetooth service...
Jan 01 13:32:35 raspberrypi bluetoothd[22096]: Bluetooth daemon 5.55
Jan 01 13:32:35 raspberrypi bluetoothd[22096]: **src/main.c:check_options() Unknown key JustWorksRepairing for group Policy in /etc/bluetooth/main.conf**
Jan 01 13:32:35 raspberrypi systemd[1]: Started Bluetooth service.
Jan 01 13:32:35 raspberrypi bluetoothd[22096]: Starting SDP server
Jan 01 13:32:35 raspberrypi bluetoothd[22096]: Bluetooth management interface 1.18 initialized
Jan 01 13:32:35 raspberrypi bluetoothd[22096]: **profiles/sap/server.c:sap_server_register() Sap driver initialization failed.**
Jan 01 13:32:35 raspberrypi bluetoothd[22096]: **sap-server: Operation not permitted (1)**
Jan 01 13:32:35 raspberrypi bluetoothd[22096]: **Failed to set privacy: Rejected (0x0b)**

The Keyword JustWorksRepairing  is set in the Policy section but not in the General section:

**[General]**
#Name = BlueZ
#Class = 0x000100
DiscoverableTimeout = 0
#AlwaysPairable = false
PairableTimeout = 0
#DeviceID = bluetooth:1234:5678:abcd
#ReverseServiceDiscovery = true
#NameResolving = true
#DebugKeys = false
#ControllerMode = dual
#MultiProfile = off
#FastConnectable = false
**#JustWorksRepairing = never**

...

[Policy]
#
#ReconnectUUIDs=00001112-0000-1000-8000-00805f9b34fb,0000111f-0000-1000-8000-00805f9b34fb,0000110a-0000-1000-8000-00805f9b34fb
#ReconnectAttempts=7
#ReconnectIntervals=1,2,4,8,16,32,64
AutoEnable=true
**JustWorksRepairing=always
#dgtcentaurmods**

We should better replace the line in main.conf in General section than adding a new one.

**second** "Failed to set privacy: Rejected (0x0b)"

kill the bluetoothd manually and run bluetoothd with -d -n

D-Bus setup failed: Connection ":1.78" is not allowed to own the service "org.bluez" due to security policies in the configuration file
bluetoothd[22178]: src/main.c:main() Unable to get on D-Bus

I found that you might try adding this flag to the ExecStart= line in bluetooth.service: '--noplugin=sap' as a solution but I wonder why it has not been used in /etc/systemd/system/bluetooth.target.wants/bluetooth.service  we modify during postinst ?

Another finding that tells me that /etc/systemd/system/bluetooth.target.wants/bluetooth.service  is not used at all:

we set in postinst -> 

ExecStart=/usr/lib/bluetooth/bluetoothd --compat --noplugin=sap,battery

BUT
 /usr/lib/bluetooth/bluetoothd
-bash: /usr/lib/bluetooth/bluetoothd: No such file or directory

Another finding:

In your /etc/systemd/system/ you should see a dbus-org.bluez.service which is symlinked and aliased from the /lib/systemd/system/bluetooth.service file.

lrwxrwxrwx  1 root root   37 Oct 30 13:14 dbus-org.bluez.service -> /lib/systemd/system/bluetooth.service

Once the /etc/systemd/system/dbus-org.bluez.service is modified by the postinst script it is no longer a symbolic link?!

Altogether we probably should not change the default service files at all but use a service override:

See https://raspberrypi.stackexchange.com/questions/40839/sap-error-on-bluetooth-service-status

If you don't want to overwrite the system bluetooth.service file, it's a good place to use a .service.d override:

sudo mkdir  /etc/systemd/system/bluetooth.service.d/

Then place in this file:

/etc/systemd/system/bluetooth.service.d/01-disable-sap-plugin.conf

[Service]
ExecStart=
ExecStart=/usr/libexec/bluetooth/bluetoothd --compat --noplugin=sap,battery

and

/etc/systemd/system/bluetooth.service.d/02-sdptool-add-SP.conf

[Service]
ExecStartPost=
ExecStartPost=/usr/bin/sdptool add SP

I reverted the changes in files below to the Bullseye defaults 

/etc/systemd/system/bluetooth.target.wants/bluetooth.service 

and 

/etc/systemd/system/dbus-org.bluez.service

pi@raspberrypi:~/backup $ sudo systemctl daemon-reload && sudo systemctl restart bluetooth.service && sudo systemctl status bluetooth.service
● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; disabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/bluetooth.service.d
             └─**01-disable-sap-plugin.conf, 02-sdptool-add-SP.conf**
     Active: active (running) since Sat 2022-01-01 14:12:29 CET; 462ms ago
       Docs: man:bluetoothd(8)
    Process: 22562 ExecStartPost=/usr/bin/sdptool add SP (code=exited, status=0/SUCCESS)
   Main PID: 22561 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 415)
        CPU: 400ms
     CGroup: /system.slice/bluetooth.service
             └─22561 /usr/libexec/bluetooth/bluetoothd --compat --noplugin=sap,battery

Jan 01 14:12:28 raspberrypi systemd[1]: Starting Bluetooth service...
Jan 01 14:12:28 raspberrypi bluetoothd[22561]: Bluetooth daemon 5.55
Jan 01 14:12:28 raspberrypi bluetoothd[22561]: src/main.c:check_options() Unknown key JustWorksRepairing for group Policy in /etc/bluetooth/main.conf
Jan 01 14:12:28 raspberrypi bluetoothd[22561]: Starting SDP server
Jan 01 14:12:28 raspberrypi bluetoothd[22561]: Excluding (cli) sap
Jan 01 14:12:28 raspberrypi bluetoothd[22561]: Excluding (cli) battery
Jan 01 14:12:28 raspberrypi bluetoothd[22561]: Bluetooth management interface 1.18 initialized
Jan 01 14:12:29 raspberrypi sdptool[22562]: Serial Port service registered
Jan 01 14:12:29 raspberrypi systemd[1]: Started Bluetooth service.

I have to run some further tests on my Pi Zero W2  connected in the Centaur running Bullseye but this already looks far better now.

**Comment by cyberluke** [comment]
I wrote about this on Discord in support. You need to run DGTCentaurMods.service as root in /etc/system.d/system or you need to change permission for /var/run/sdp. Then it will work. The second option needs to be run on every restart or app start, how to is here: https://stackoverflow.com/questions/34599703/rfcomm-bluetooth-permission-denied-error-raspberry-pi

This is tested by me, both methods are possible. This is for operation not permitted or similar. Of course you need to fix symlinks. I dont know why I had this symlink pointed to /lib/systemd/system/bluetooth.service. It was a fresh Bullseye install with apt update and upgrade, last week.

**Comment by marcb1309** [comment]
Thanks luke. 
I just tried to document yours and my findings and find a way to configure all.

Further more we will have to add a "trigger" service that will change permissions of /var/run/sdp whenever it it created with permission root:root and changed to root:bluetooth and add user pi to bluetooth group during installation.

**Comment by marcb1309** [comment]
in /etc/systemd/system create  

var-run-sdp.path 

[Unit]
Descrption=Monitor /var/run/sdp

[Install]
WantedBy=bluetooth.service

[Path]
PathExists=/var/run/sdp
Unit=var-run-sdp.service

AND

var-run-sdp.service 

[Unit]
Description=Set permission of /var/run/sdp

[Install]
RequiredBy=var-run-sdp.path

[Service]
Type=simple
ExecStart=sudo /bin/chgrp bluetooth /var/run/sdp

see  [https://github.com/ev3dev/ev3dev/issues/274](https://github.com/ev3dev/ev3dev/issues/274)

**Comment by marcb1309** [comment]
All those changes could be added by file in the debian package rather than modifying in postinst script!

**Comment by wormstein** [comment]
We can put this file  in /etc with the rest of services and inject in the Deb. Postinst will auto deploy and we just make sure to enable this

**Comment by wormstein** [comment]
Couldn't we just use ExecPost directive in Bluetooth service instead to run /bin/chgrp bluetooth /var/run/sdp? Maybe prepend a sleep command to give some delay...

**Comment by cyberluke** [comment]
I think that could work, it could be just one script. It is strange that this issue is generic Debian/Bluetooth issue and there is no official help. I would expect Rasbian should have these scripts out of the box or there would be step by step guide for BLE and Bluetooth tutorial.

**Comment by marcb1309** [comment]
Confirmed fixed in latest commit to master branch. Note that you would need to build the debian package and install on a "new" Bullseye install.

Bluetooth DGT and millenium may still need further testing and maybe even fixes but at least we do not see any more exceptions while starting up the services. 

pi@dgtcentaur:~ $ service bluetooth status
● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/bluetooth.service.d
             └─01-disable-sap-plugin.conf, 02-sdptool-add-SP.conf
     Active: active (running) since Thu 2022-01-13 00:29:20 CET; 4min 4s ago
       Docs: man:bluetoothd(8)
    Process: 548 ExecStartPost=/usr/bin/sdptool add SP (code=exited, status=0/SUCCESS)
   Main PID: 547 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 409)
        CPU: 168ms
     CGroup: /system.slice/bluetooth.service
             └─547 /usr/libexec/bluetooth/bluetoothd --compat --noplugin=sap,battery

Jan 13 00:29:19 dgtcentaur systemd[1]: Starting Bluetooth service...
Jan 13 00:29:20 dgtcentaur bluetoothd[547]: Bluetooth daemon 5.55
Jan 13 00:29:20 dgtcentaur bluetoothd[547]: Starting SDP server
Jan 13 00:29:20 dgtcentaur bluetoothd[547]: Excluding (cli) sap
Jan 13 00:29:20 dgtcentaur bluetoothd[547]: Excluding (cli) battery
Jan 13 00:29:20 dgtcentaur bluetoothd[547]: Bluetooth management interface 1.18 initialized
Jan 13 00:29:20 dgtcentaur sdptool[548]: Serial Port service registered
Jan 13 00:29:20 dgtcentaur systemd[1]: Started Bluetooth service.


pi@dgtcentaur:~ $ ls -la /var/run/sdp
srw-rw---- 1 root **bluetooth** 0 Jan 13 00:29 /var/run/sdp

**Comment by thefoster** [comment]
Hmm, although /var/run/sdp has the permissions stated here, i'm still getting the error message (Failed to start Set permission of /var/run/sdp) on a fresh install with mods deb 1.3.2.
